services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URL: db:5432
    volumes:
      - ./backend/src/:/app/src/
    ports:
      - "8000:8000"
    networks:
      - shared-network
      - app-network

  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
      --allowed-hosts mlflow:5000
    volumes:
      - mlflow_artifacts:/mlflow
    environment:
      - MLFLOW_HOST=0.0.0.0
      - MLFLOW_ALLOW_ALL_HOSTS=true
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - app-network

  trainer:
    build: ./trainer
    container_name: recommender-trainer
    profiles: ["train"]
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./trainer/src:/app/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - mlflow
      - db
    networks:
      - app-network
    working_dir: /app/src
    command: ["python", "train.py"]

  bento:
    build: ./bento
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

  shared-network:
    external: true

volumes:
  pg_data:
  mlflow_artifacts: